name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - Front-CloudStorage

permissions:
  id-token: write
  contents: read

env:
  REGION: europe-west1
  REPO_NAME: cartwish-repo
  BACKEND_NAME: cartwish-backend
  FRONTEND_NAME: cartwish-frontend-bucket-${{ secrets.PROJECT_ID }}
  IMAGE_TAG: ${{ github.sha }}


jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.check_backend.outputs.changed }}
      frontend_changed: ${{ steps.check_frontend.outputs.changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{secrets.SERVICE_ACCOUNT_EMAIL}}

      - name: Test gsutil upload
        run: |
          echo "test" > testfile.txt
          gsutil cp testfile.txt gs://cartwish-frontend-bucket-${{ secrets.PROJECT_ID }}/


      - name: Check if backend changed
        id: check_backend
        run: |
          git fetch origin main --depth=2
          if git diff --quiet HEAD^ HEAD -- backend; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Check if frontend changed
        id: check_frontend
        run: |
          git fetch origin main --depth=2
          if git diff --quiet HEAD^ HEAD -- frontendJS; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build & Push backend image
        if: steps.check_backend.outputs.changed == 'true'
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/cartwish-repo/backend:${{ env.IMAGE_TAG }} ./backend
          docker push europe-west1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/cartwish-repo/backend:${{ env.IMAGE_TAG }}

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Deploy backend to Cloud Run 
        if: steps.check_backend.outputs.changed == 'true'
        working-directory: ./infra
        run: terraform apply -auto-approve -target=module.backend -var="backend_image_tag=${{ env.IMAGE_TAG }}"

      - name: Get current backend URL from Cloud Run
        id: backend_url
        run: |
          url=$(gcloud run services describe ${{ env.BACKEND_NAME }} \
            --region ${{ env.REGION }} \
            --format='value(status.url)')
          echo "BACKEND_URL=$url" >> $GITHUB_OUTPUT

      - name: Install Node.js
        if: steps.check_frontend.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build frontend
        if: steps.check_frontend.outputs.changed == 'true'
        working-directory: ./frontendJS
        env:
          VITE_API_URL: ${{ steps.backend_url.outputs.BACKEND_URL }}/api
        run: |
          npm ci
          npm run build -- --base=/

      - name: Deploy frontend bucket
        if: steps.check_frontend.outputs.changed == 'true'
        working-directory: ./infra
        run: terraform apply -auto-approve -target=module.frontend


      - name: Upload frontend to Cloud Storage
        if: steps.check_frontend.outputs.changed == 'true'
        run: |
          gsutil -m rsync -r ./frontendJS/dist gs://cartwish-frontend-bucket-${{ secrets.PROJECT_ID }}/

      - name: Output Cloud Run and Storage URLs
        working-directory: ./infra
        run: terraform output