name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - FullLoadBalancerArc

permissions:
  id-token: write
  contents: read

env:
  REGION: europe-west1
  REPO_NAME: cartwish-repo
  BACKEND_NAME: cartwish-backend
  FRONTEND_NAME: cartwish-frontend
  IMAGE_TAG: ${{ github.sha }}


jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{secrets.SERVICE_ACCOUNT_EMAIL}}

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build & Push backend image
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/cartwish-repo/backend:${{ env.IMAGE_TAG }} ./backend
          docker push europe-west1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/cartwish-repo/backend:${{ env.IMAGE_TAG }}

      - name: Build & Push frontend image 
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/cartwish-repo/frontend:${{ github.sha }} ./frontendJS
          docker push europe-west1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/cartwish-repo/frontend:${{ github.sha }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init
      
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="backend_image_tag=${{ env.IMAGE_TAG }}" \
            -var="frontend_image_tag=${{ env.IMAGE_TAG }}" \
            -var="database_url_secret=${{ secrets.DB_URL }}" \
            -var="jwt_secret_value=${{ secrets.JWT_SECRET }}"
        working-directory: ./infra

      - name: Output Cloud Run URLs
        working-directory: ./infra
        run: terraform output

